USE [master]
GO

/****** Object:  Database [RPSAnnounceDB]    Script Date: 03/28/2010 10:04:13 ******/
CREATE DATABASE [RPSAnnounceDB] ON  PRIMARY 
( NAME = N'RPSAnnounceDB', FILENAME = N'C:\Announcements\Database\RPSAnnounceDB.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RPSAnnounceDB_log', FILENAME = N'C:\Announcements\Database\RPSAnnounceDB_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RPSAnnounceDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RPSAnnounceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RPSAnnounceDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RPSAnnounceDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RPSAnnounceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RPSAnnounceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RPSAnnounceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RPSAnnounceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RPSAnnounceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RPSAnnounceDB] SET  READ_WRITE 
GO

ALTER DATABASE [RPSAnnounceDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RPSAnnounceDB] SET  MULTI_USER 
GO

ALTER DATABASE [RPSAnnounceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RPSAnnounceDB] SET DB_CHAINING OFF 
GO

